### ISSUE TITLE
I believe there is a bug in BreadcrumbsXGCN_library/XGCN/dataloading/sample /pos_sampler.py

### ISSUE THREAD

**Issue by Dengyingjie** [CGCL-codes/XGCN_library#2]
First of all, this is a very useful project, and I learned a lot from it，thanks！

By the way, I found a bug in XGCN_library/XGCN/dataloading/sample/pos_sampler.py

`
if len(nei) == 0: 
                pos.append(src) # => here, should be pos.append(u)
`

**Comment by xiransong** [comment]
Thank you for discovering this bug! We have fixed it in the latest version.
